---
 
- name: Download Alert deployment scripts from artifactory
  copy: src=deploymentScripts.gz dest=/home/vasu mode=0755

- name: Unzip folder  
  command: gtar -zxvf deploymentScripts.gz
  
- name: Going inside scripts folder3   
  shell: cd scripts/java-properties/ && chmod 755 deploy-properties.sh  && ./deploy-properties.sh vasu $PLATFORM 
  
- name: Stoping Alarming 
  shell: ./scripts/alarmd-control.sh chmod 755 vasu $PLATFORM SHUTDOWN
  
- name: Deploying Java Managers"
  shell: chmod 755 ./scripts/mgr-deployment-art.sh -n -l $PLATFORM -u vasu -s 2 -p $MANAGER -m 2 -v ${VERSION} -r
  
- name: Sleeping for 5 seconds, then checking on managers  
  shell: sleep 15 
  shell: ./scripts/mgr-service-setup.sh chmod 755 --user vasu --location $PLATFORM --mode QUERY_CHANGING
  
- name: Clearing and Starting Alarming Back Up
  shell: ./scripts/alarmd-control.sh chmod 755 vasu BETA STARTUP > /tmp/testscript.log 

           

  

       
