---
- name: Download Alert deployment scripts from artifactory
  shell: wget "https://artifacts.west.com/artifactory/libs-snapshot-local/com/tfcci/ucs/TFCCAlert/4.3.1-SNAPSHOT/"
         dest: /home/vasu
         mode: 0755
          
