---
- name: Download Alert deployment scripts from artifactory
  command: wget /Users/vasudevramisetti/downloads/deploymentScripts.gz
          dest: /home/vasu
          mode: 0755
           

  

        
