---
- name: Download Alert deployment scripts from artifactory
  get_url:
          url: https://led35658.wic.west.com:443/artifactory/libs-snapshot-local/com/tfcci/ucs/TFCCAlert/4.3.1-SNAPSHOT/TFCCAlert-4.3.1-20180511.185914-1.deploymentScripts.tar.gz
          dest: /home/vasu
          mode: 0755
          
