---
- name: Download Alert deployment scripts from artifactory
  command: wget "http://artifacts.west.com/artifactory/libs-snapshot/com/tfcci/ucs/TFCCAlert/${VERSION}/TFCCAlert-${VERSION}.deploymentScripts.tar.gz" -O deploymentScripts.gz
  dest: /home/vasu
          
