---
- name: Echo env variable version check 
  shell: echo "Version: " $VERSION
  
- name: Download Alert deployment scripts from artifactory
  copy: src=deploymentScripts.gz dest=/home/vasu mode=0755

- name: Unzip folder  
  command: gtar -zxvf deploymentScripts.gz
  
- name: Going inside scripts folder3   
  shell: cd scripts/java-properties/ && chmod 755 deploy-properties.sh  && ./deploy-properties.sh vasu $PLATFORM > /tmp/testscript.log 


           

  

       
