--- 
- 
  become: true
  become_user: tfccdply
  name: "trying to access with service account"
  tasks: 
    - 
      name: "Please print on server what i mentioned here."
      shell: "echo \"Hi! Tower is working with vasudev credentials.\""
