---
- name: Download Alert deployment scripts from artifactory
  copy: src=deploymentScripts.gz dest=/home/vasu
  mode: 0755
- name: unzip folder   
  command: gunzip deploymentScripts.gz
  command: cd deploymentScripts/scripts/java-properties
 
           

  

       
