---
 
- name: Download Alert deployment scripts from artifactory
  copy: src=deploymentScripts.gz dest=/home/vasu mode=0755

- name: Unzip folder  
  command: gtar -zxvf deploymentScripts.gz
  
- name: Going inside scripts folder3   
  shell: cd scripts/java-properties/ && chmod 755 deploy-properties.sh  && ./deploy-properties.sh vasu $PLATFORM 
  
- name: Stoping Alarming    
  shell: cd scripts/ && chmod 755 alarmd-control.sh && ./alarmd-control.sh -u vasu $PLATFORM SHUTDOWN

##########
# - name: Deploying Java Managers"
#   shell: cd scripts && chmod 755 mgr-deployment-art.sh && ./mgr-deployment-art.sh -n -l $PLATFORM -u vasu -s 2 -p $MANAGER -m 2 -v ${VERSION} -r
##########

- name: Sleeping for 5 seconds, then checking on managers  
  shell: sleep 15 
  shell: cd scripts && chmod 755 mgr-service-setup.sh && ./mgr-service-setup.sh -u vasu --location $PLATFORM --mode QUERY_CHANGING
  
- name: Clearing and Starting Alarming Back Up
  shell: cd scripts && chmod 755 alarmd-control.sh && ./alarmd-control.sh -u vasu BETA STARTUP > /tmp/testscript.log 

           

  

       
