---
- name: Download Alert deployment scripts from artifactory
  copy: src=deploymentScripts.gz dest=/home/vasu mode=0755

- name: Unzip folder  
  command: gtar -zxvf deploymentScripts.gz
  
- name: Going inside scripts folder   
  shell: cd scripts/java-properties
  
           

  

       
