---
- name: Download Alert deployment scripts from artifactory
  get_url:
          url: http://artifacts.sandbox.west.com/artifactory/libs-snapshot-local/com/tfcci/bureau/manager/1.3.174-SNAPSHOT/manager-1.3.174-20180430.184058-1.deploymentScripts.tar.gz
          dest: /home/vasu/
          mode: 0777
          
