---
- name: Download Alert deployment scripts from artifactory
  get_url:
          url: https://artifacts.west.com/artifactory/libs-snapshot-local/com/tfcci/ucs/TFCCAlert/4.3.1-SNAPSHOT/TFCCAlert-4.3.1-20180511.185914-1.deploymentScripts.tar.gz
          dest: home/vasu mode=0777
          
