---
- name: Download Alert deployment scripts from artifactory
  copy: src=deploymentScripts.gz dest=/home/vasu
  mode: 0755
- name: unzip folder   
  command: gtar -zxvf deploymentScripts.gz
  command: cd scripts/java-properties
  shell: ./deploy-properties.sh tfccdply $PLATFORM
           

  

       
