---
- name: Trying to access service account.
  become: yes
  become_user: tfccdply

  tasks:
    -
      name: "Please print on server what i mentioned here."
      shell: "echo \"Hi! Tower is working with vasudev credentials.\""
    
