---
- name: Vasudev is Transfering and execute a script.
  hosts: all
  remote_user: tfccdply

  tasks:
     - name: Taking script from source Transfer the script 
       shell: echo "Hi! Tower is working with vasudev credentials." 
